[versions]
bouncyCastle = "1.70"
grpc = "1.44.0"
jackson = "2.13.2"
jacksonProtobuf = "0.9.12"
kotlin = "1.6.10"
kotlinCoroutines = "1.5.2"
mockk = "1.12.4"
okHttp = "4.9.3"
protobuf = "3.20.1"
provenanceClient = "1.0.5"
provenanceEventStream = "0.6.0"
provenanceHdWallet = "0.1.15"
provenanceProto = "1.9.0"
provenanceScope = "0.4.9"
scarlet = "0.1.12"

[libraries]
bouncyCastleBcProv = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncyCastle" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
coroutinesCoreJvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinCoroutines" }
coroutinesJdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinCoroutines" }
coroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinCoroutines" }
grpcNettyShaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpcProtobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpcStub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
jacksonDataTypeJdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jacksonDataTypeJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jacksonKotlinModule = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jacksonProtobufModule = { module = "com.hubspot.jackson:jackson-datatype-protobuf", version.ref = "jacksonProtobuf" }
kotlinAllOpen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinStdLibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okHttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobufJavaUtil = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
provenanceEventStreamApi = { module = "io.provenance.eventstream:es-api", version.ref = "provenanceEventStream" }
provenanceEventStreamApiModel = { module = "io.provenance.eventstream:es-api-model", version.ref = "provenanceEventStream" }
provenanceEventStreamCore = { module = "io.provenance.eventstream:es-core", version.ref = "provenanceEventStream" }
provenanceGrpcClient = { module = "io.provenance.client:pb-grpc-client-kotlin", version.ref = "provenanceClient" }
provenanceHdWallet = { module = "io.provenance.hdwallet:hdwallet", version.ref = "provenanceHdWallet" }
provenanceProto = { module = "io.provenance:proto-kotlin", version.ref = "provenanceProto" }
provenanceScopeEncryption = { module = "io.provenance.scope:encryption", version.ref = "provenanceScope" }
provenanceScopeUtil = { module = "io.provenance.scope:util", version.ref = "provenanceScope" }
scarlet = { module = "com.tinder.scarlet:scarlet", version.ref = "scarlet" }
scarletMessageAdapterMoshi = { module = "com.tinder.scarlet:message-adapter-moshi", version.ref = "scarlet" }
scarletStreamAdapterCoroutines = { module = "com.tinder.scarlet:stream-adapter-coroutines", version.ref = "scarlet" }
scarletWebSocketOkHttp = { module = "com.tinder.scarlet:websocket-okhttp", version.ref = "scarlet" }

# This doesn't current work in a way that's useful.  Keeping this here for a magical future where it's relevant
[plugins]
idea = { id = "idea" }

[bundles]
coroutines = ["coroutinesCore", "coroutinesCoreJvm", "coroutinesReactor", "coroutinesJdk8"]
eventStream = ["provenanceEventStreamApi", "provenanceEventStreamApiModel", "provenanceEventStreamCore"]
grpc = ["grpcNettyShaded", "grpcProtobuf", "grpcStub"]
jackson = ["jacksonDataTypeJdk8", "jacksonDataTypeJsr310", "jacksonKotlinModule", "jacksonProtobufModule"]
kotlin = ["kotlinAllOpen", "kotlinReflect", "kotlinStdLibJdk8"]
protobuf = ["protobufJava", "protobufJavaUtil"]
provenance = ["provenanceGrpcClient", "provenanceHdWallet", "provenanceProto", "provenanceScopeEncryption", "provenanceScopeUtil"]
scarlet = ["scarletMessageAdapterMoshi", "scarlet", "scarletStreamAdapterCoroutines", "scarletWebSocketOkHttp"]
test = ["kotlinTest", "mockk"]
